### ISSUE TITLE
Running on server

### ISSUE THREAD

**Issue by matanki-saito** [oooFUNooo/henrietta#1]
サーバ上で動かすアドバイスのissueです。
azureやawsはいろいろと調整が必要なため、herokuでやると良いと思います。下記参考になりますか？
https://qiita.com/1ntegrale9/items/9d570ef8175cf178468f

**Comment by oooFUNooo** [comment]
ここまで完了。
- herokuアカウントの取得
- 必要な環境の構築
- サンプルアプリのデプロイ

**Comment by oooFUNooo** [comment]
辞書を読み込ませる方法がわからない・・・
もしかして、レポジトリに辞書を丸ごと放り込むしかない？

**Comment by matanki-saito** [comment]
辞書はparatranzからダウンロードしてきたzipファイルを元にしていますか？
アプリの起動時に、paratranzからダウンロードするようにしても良いかもしれません

**Comment by matanki-saito** [comment]
https://github.com/matanki-saito/CK2JPModAppendixI/blob/3cfb53a0ec946e3136cadd186c93b5fc5d8a684a/main.py#L18

**Comment by oooFUNooo** [comment]
ブレイクスルーに到達

**Comment by oooFUNooo** [comment]
EU4版とCK2版を同時に動かす方法はこれで解決か？
[https://qiita.com/1ntegrale9/items/d0010489fbeb50aee618](https://qiita.com/1ntegrale9/items/d0010489fbeb50aee618)

**Comment by oooFUNooo** [comment]
処理をクラスにまとめる方法がわからず、EU4版とCK2版が並存する気持ち悪いコードになったけど、
幾多の困難を乗り越えついに動作成功！
